# Numpy科学计算  

numpy 是 python科学计算的核心库。PYTHON里涉及到科学计算的包括Pandas,sklearn等都是基于numpy进行二次开发包装的。numpy功能非常强大，和scipy构建了强大的PYTHON数理计算功能，函数接口丰富复杂。

<img src="http://wx1.sinaimg.cn/mw690/d409b13egy1fo90o5jtpqj211i09wjuc.jpg" width = "500" height = "300" alt="图片名称" align=center />

对于本次课程来说，我们重点学习的是以下几点：
    1. 数组的定义和应用
    2. 数组元素的索引选取
    3. 数组的计算
   
![](https://jalammar.github.io/images/numpy/numpy-array.png)

## 数组：Arrays

array用来存储同类型的序列数据，能够被非负整数进行索引。 维度的数量就是array的秩(rank)。

我们可以通过python的列表来创建array,并且通过方括号进行索引获取元素


![](https://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [1]:

import numpy as np 
a = np.array([1,3,4,6,10])


In [6]:
a

array([ 1,  3,  4,  6, 10])

In [7]:
#print(a)

print(a.size)
print(a.shape)
print(a[2])

5
(5,)
4


**高维数组的创建**

![](https://jalammar.github.io/images/numpy/numpy-3d-array.png)

不同维度之间使用逗号分隔即可

![](https://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

In [9]:
# 二维数组

b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)
b[0,1]

(2, 4)


2

In [10]:
b = np.array([[[1,2,3,4],[5,6,7,8]]])

In [11]:
print(b.shape)

(1, 2, 4)


In [12]:
b

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

## 创建Array
numpy提供了内置的函数来创建一些特殊的数组，我们仅仅需要传递创建的大小即可
![](https://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
b = np.ones([3,3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
b.shape

(3, 3)

In [16]:
np.zeros_like(b)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array的常用属性和方法

* 统计计算
* 排序
* 按照大小查索引
* 条件查找
* shape

In [18]:
a = np.random.rand(3,4)
a.shape

(3, 4)

In [19]:
a

array([[0.19042425, 0.78446022, 0.39015823, 0.63940876],
       [0.05795014, 0.03221913, 0.64515246, 0.65068161],
       [0.69503537, 0.91160515, 0.12402847, 0.56974398]])

In [20]:
a.size

12

In [21]:
len(a)

3

In [23]:
# 排序
np.sort(a,axis = 1)

array([[0.19042425, 0.39015823, 0.63940876, 0.78446022],
       [0.03221913, 0.05795014, 0.64515246, 0.65068161],
       [0.12402847, 0.56974398, 0.69503537, 0.91160515]])

In [24]:
np.sort(a)

array([[0.19042425, 0.39015823, 0.63940876, 0.78446022],
       [0.03221913, 0.05795014, 0.64515246, 0.65068161],
       [0.12402847, 0.56974398, 0.69503537, 0.91160515]])

In [26]:
a

array([[0.19042425, 0.78446022, 0.39015823, 0.63940876],
       [0.05795014, 0.03221913, 0.64515246, 0.65068161],
       [0.69503537, 0.91160515, 0.12402847, 0.56974398]])

In [25]:
# Returns the indices that would sort this array.
a.argsort()

array([[0, 2, 3, 1],
       [1, 0, 2, 3],
       [2, 3, 0, 1]], dtype=int64)

In [27]:
# Return elements, either from `x` or `y`, depending on `condition`.
# If only `condition` is given, return ``condition.nonzero()``
np.where(a>0.5)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 3, 2, 3, 0, 1, 3], dtype=int64))

In [28]:
a > 0.5

array([[False,  True, False,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [32]:
np.where(a>0.5,a,0)

array([[0.        , 0.78446022, 0.        , 0.63940876],
       [0.        , 0.        , 0.64515246, 0.65068161],
       [0.69503537, 0.91160515, 0.        , 0.56974398]])

In [33]:
a[np.where(a>0.5)]

array([0.78446022, 0.63940876, 0.64515246, 0.65068161, 0.69503537,
       0.91160515, 0.56974398])

**聚合计算**

我们可以对数组应用常用的聚合函数
![](https://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)



可以通过指定axis，表明函数在某个维度上进行计算
![](https://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [35]:
a

array([[0.19042425, 0.78446022, 0.39015823, 0.63940876],
       [0.05795014, 0.03221913, 0.64515246, 0.65068161],
       [0.69503537, 0.91160515, 0.12402847, 0.56974398]])

In [34]:
a.sum(axis = 1)

array([2.00445145, 1.38600334, 2.30041297])

In [38]:
np.sum(a)
np.sum(a,axis = 1)
np.sum(a,axis = 0)

array([0.94340976, 1.7282845 , 1.15933916, 1.85983435])

In [39]:
np.mean(a)
np.std(a)

0.2903975474933238

In [ ]:
a

## Shape改变
一个数组的 shape 是由轴及其元素数量决定的，它一般由一个整型元组表示，且元组中的整数表示对应维度的元素数

我们最容易接触到的shape改变就是转置，这通常用于计算dot

![](https://jalammar.github.io/images/numpy/numpy-transpose.png)

还有一种常见的情形是在机器学习中应用，我们需要改变数组的形状从而适应我们的建模需要

![](https://jalammar.github.io/images/numpy/numpy-reshape.png)

In [40]:
import numpy as np
a = np.random.randint(1,100,size =(5,6))
a.shape

(5, 6)

In [41]:
a

array([[35, 17, 33, 66, 45, 44],
       [70, 53, 27, 74, 15,  5],
       [84, 38,  8, 70, 85, 54],
       [53, 88, 12, 55, 29,  4],
       [ 8, 80, 17, 41, 47, 73]])

一个数组的 shape 可以由许多方法改变。例如以下三种方法都可输出一个改变 shape 后的新数组，它们都不会改变原数组。其中 reshape 方法在实践中会经常用到，因为我们需要改变数组的维度以执行不同的运算。

In [42]:
a.ravel()

array([35, 17, 33, 66, 45, 44, 70, 53, 27, 74, 15,  5, 84, 38,  8, 70, 85,
       54, 53, 88, 12, 55, 29,  4,  8, 80, 17, 41, 47, 73])

In [45]:
a.reshape(10,3)

array([[35, 17, 33],
       [66, 45, 44],
       [70, 53, 27],
       [74, 15,  5],
       [84, 38,  8],
       [70, 85, 54],
       [53, 88, 12],
       [55, 29,  4],
       [ 8, 80, 17],
       [41, 47, 73]])

In [46]:
a.T 

array([[35, 70, 84, 53,  8],
       [17, 53, 38, 88, 80],
       [33, 27,  8, 12, 17],
       [66, 74, 70, 55, 41],
       [45, 15, 85, 29, 47],
       [44,  5, 54,  4, 73]])

ravel() 和 flatten() 都是将多维数组降到一维，flatten() 返回一份新的数组，且对它所做的修改不会影响原始数组.

In [47]:
a.flatten()

array([35, 17, 33, 66, 45, 44, 70, 53, 27, 74, 15,  5, 84, 38,  8, 70, 85,
       54, 53, 88, 12, 55, 29,  4,  8, 80, 17, 41, 47, 73])

In [48]:
a.ravel()

array([35, 17, 33, 66, 45, 44, 70, 53, 27, 74, 15,  5, 84, 38,  8, 70, 85,
       54, 53, 88, 12, 55, 29,  4,  8, 80, 17, 41, 47, 73])

如果在 shape 变换中一个维度设为 - 1，那么这一个维度包含的元素数将会被自动计算。如下所示，a 一共有 30 个元素，在确定一共有 3 行后，-1 会自动计算出应该需要 10 列才能安排所有的元素。

In [52]:
a.reshape(-1,4)

ValueError: cannot reshape array of size 30 into shape (4)

## 随机数

numpy可以根据一定的规则创建随机数，随机数的使用会在后面概率论，数据挖掘的时候经常用到。

官方主页[RANDOM](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

常用的一些方法：

* rand(d0, d1, ..., dn)	Random values in a given shape.
* randn(d0, d1, ..., dn)	Return a sample (or samples) from the “standard normal” distribution.
* randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).
* random([size])	Return random floats in the half-open interval [0.0, 1.0).
* sample([size])	Return random floats in the half-open interval [0.0, 1.0).
* choice(a[, size, replace, p])	Generates a random sample from a given 1-D array

In [53]:
np.random.rand(10)
np.random.rand(3,4)

array([[0.13213639, 0.10483424, 0.73948518, 0.21761492],
       [0.73116334, 0.6819338 , 0.5574819 , 0.60292815],
       [0.29789809, 0.25146472, 0.38916319, 0.62778632]])

In [ ]:
np.random.rand(10,1,3,5)

In [57]:
np.random.randn(5,4)

array([[-0.94075815, -1.59641474,  0.30138377,  0.44422446],
       [-0.96285352,  0.87031482,  0.08230303, -1.44699517],
       [-0.78762155,  1.67323876, -1.21028471, -0.31364664],
       [ 1.5073839 ,  0.68224342,  0.31137836,  0.19462174],
       [-0.02909675, -0.82715069, -0.37949312, -0.14153809]])

In [76]:
np.random.randint(10)
np.random.randint(1,10,size = (3,4,2))

array([[[9, 6],
        [3, 2],
        [7, 9],
        [4, 1]],

       [[1, 2],
        [4, 6],
        [2, 8],
        [7, 4]],

       [[2, 1],
        [6, 8],
        [8, 2],
        [6, 9]]])

In [80]:
np.random.random((2,5,2))

array([[[0.64285893, 0.00973211],
        [0.3877431 , 0.00279222],
        [0.92579284, 0.90993454],
        [0.32011758, 0.55662952],
        [0.03475818, 0.43476543]],

       [[0.17215763, 0.51142994],
        [0.94863365, 0.65214166],
        [0.76066994, 0.79601799],
        [0.08163268, 0.10906872],
        [0.33978848, 0.95127167]]])

In [84]:
np.random.choice(10,(3,4))

array([[0, 6, 3, 5],
       [9, 5, 2, 5],
       [0, 1, 1, 3]])

In [81]:
np.random.choice([1,4,5,7.08],(3,4))

array([[5.  , 5.  , 1.  , 7.08],
       [1.  , 4.  , 5.  , 7.08],
       [4.  , 4.  , 4.  , 7.08]])

In [82]:
?np.random.choice

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

        .. versionadded:: 1.7.0

Parameters
-----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if a were np.arange(a)
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given the sample assumes a uniform distribution over all
    entries in a.

Returns
--------
samples : single item or ndarray
    The generated random samples

Raises
-------
ValueError
    If a is an int and less than zero, if a or p are not 1-dimensional,
    if a is an array-like of siz

## 数组的索引

**切片**选取类似于list，但是array可以是多维度的，因此我们需要指定每一个维度上的操作

![](https://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

In [85]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # 2维数组，shape = 3 * 4

In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
a[1:3,0:1]
a[:,:1]

array([[1],
       [5],
       [9]])

**整数索引**

In [93]:
a[[1,2],[0,1]]

array([ 5, 10])

**布尔型索引**

In [95]:
a >4
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

**图解索引**

<img src="http://wx1.sinaimg.cn/mw690/d409b13egy1fo90ob733bj218m0hyjz3.jpg" width = "600" height = "400" alt="图片名称" align=left />

<img src="http://wx2.sinaimg.cn/mw690/d409b13egy1fo90ohhyecj21020kaage.jpg" width = "600" height = "400" alt="图片名称" align=left />



## 数学计算
![](https://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)


数组计算有广播机制，及时数组的形状不完全一样，也可以通过该机制进行计算
![](https://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png)

In [96]:
a = np.random.random([3,4])
b = np.random.random([3,4])

In [97]:
a

array([[0.08440695, 0.2671377 , 0.30167481, 0.72639598],
       [0.95945958, 0.13546652, 0.65206206, 0.03883471],
       [0.57120815, 0.54586658, 0.0901169 , 0.46938694]])

In [98]:
a + 2

array([[2.08440695, 2.2671377 , 2.30167481, 2.72639598],
       [2.95945958, 2.13546652, 2.65206206, 2.03883471],
       [2.57120815, 2.54586658, 2.0901169 , 2.46938694]])

In [99]:
a * 10

array([[0.84406949, 2.67137704, 3.01674814, 7.26395985],
       [9.59459577, 1.3546652 , 6.52062064, 0.38834713],
       [5.71208148, 5.45866584, 0.901169  , 4.69386941]])

In [100]:
b

array([[0.94139452, 0.86691587, 0.98672421, 0.46030295],
       [0.10752278, 0.01969367, 0.55021107, 0.16866977],
       [0.5011183 , 0.55170734, 0.13235043, 0.80335569]])

In [101]:
# Elementwise
a  + b
a - b
a * b
a / b

array([[0.08966161, 0.30814721, 0.30573367, 1.5780824 ],
       [8.92331405, 6.8786826 , 1.18511258, 0.23024109],
       [1.13986686, 0.9894133 , 0.68089617, 0.58428284]])

In [ ]:
# Elementwise
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)

*是元素力度的计算(Elementwise),并不是矩阵计算。我们使用dot函数进行内积求解

求积是数组计算的最重要的形式！

![](https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)

具体计算逻辑如下所示：
![](https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-2.png)

In [106]:
# shape(a) = 3*4  shape(b.T) = 4*3
a.dot(b.T) # (3*4) * (4*3) = 3 * 3
np.dot(a,b.T)

array([[0.94307821, 0.30284246, 0.81316084],
       [1.68194922, 0.47115361, 0.67303941],
       [1.31593335, 0.20092271, 0.97641314]])

In [102]:
a

array([[0.08440695, 0.2671377 , 0.30167481, 0.72639598],
       [0.95945958, 0.13546652, 0.65206206, 0.03883471],
       [0.57120815, 0.54586658, 0.0901169 , 0.46938694]])

In [105]:
b.T

array([[0.94139452, 0.10752278, 0.5011183 ],
       [0.86691587, 0.01969367, 0.55170734],
       [0.98672421, 0.55021107, 0.13235043],
       [0.46030295, 0.16866977, 0.80335569]])

## 实际应用


### 机器学习
在我们学习到后面机器学习的时候，会遇到一个公式。这个公式在统计学习中叫做最小二乘法，在机器学习中的线性回归模型中叫做平方和误差

![](https://jalammar.github.io/images/numpy/mean-square-error-formula.png)

我们转换一下公式

![](https://jalammar.github.io/images/numpy/numpy-mean-square-error-formula.png)

设定一下lable和prediction 

![](https://jalammar.github.io/images/numpy/numpy-mse-1.png)

![](https://jalammar.github.io/images/numpy/numpy-mse-2.png)

![](https://jalammar.github.io/images/numpy/numpy-mse-4.png)

### **图像**

我们在计算机保存一张灰色的图像使用的就是Numpy数组

![](https://jalammar.github.io/images/numpy/numpy-grayscale-image.png)

如果是彩色的图像，那么就是三维数组
![](https://jalammar.github.io/images/numpy/numpy-color-image.png)

### **文本**

我们可以把一句话切割成单个的字符

![](https://jalammar.github.io/images/numpy/numpy-nlp-tokenization.png)

然后可以用数字代表这些字符

![](https://jalammar.github.io/images/numpy/numpy-nlp-ids.png)

但是通常这些id不会提供很多有用的信息，我们一般会根据某种算法，将它转换成向量形式

![](https://jalammar.github.io/images/numpy/numpy-nlp-embeddings.png)